spring.application.name=product-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/productdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# DevOps Traceability: Expose the version and enable Actuator Info
info.app.version=${APP_VERSION:unknown}
management.endpoints.web.exposure.include=health,prometheus,info
management.info.env.enabled=true

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true