---
# 1. The Networking Service (So the app can find the DB)
apiVersion: v1
kind: Service
metadata:
  name: product-db
spec:
  selector:
    app: product-db
  ports:
    - port: 5432
      targetPort: 5432

---
# 2. The Deployment (The Postgres Database)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: productdb
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password