apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: productdb
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: product-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-db-secret
              key: POSTGRES_PASSWORD
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "user", "-d", "productdb"]
          initialDelaySeconds: 10
          periodSeconds: 5

        volumeMounts:
        - name: product-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: product-db-storage
        persistentVolumeClaim:
          claimName: product-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: product-db
spec:
  selector:
    app: product-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432