apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      contavanshaj@vanshaj-Dell-G15-5520:~/devops-store$ curl http://localhost:8082/actuator/health
{"groups":["liveness","readiness"],"status":"UP"}vanshaj@vanshaj-Dell-G15-5520:~/devops-store$ iners:
      - name: user-service
        image: vnj91/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082 
        env:
        - name: SERVER_PORT
          value: "8082"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://user-db:5432/userdb
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
